---
apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: micro-frontend
deploy:
  kubectl:
    manifests:
    - manifests/micro-frontend-namespace.yaml
    - manifests/platforms/*
build:
  local:
    push: false
  artifacts:
    - image: mothership
      context: platforms/mothership
      docker:
        dockerfile: ./Dockerfile
    - image: auth-app
      context: platforms/auth-app
      docker:
        dockerfile: ./Dockerfile
    - image: enterprise
      context: platforms/enterprise
      docker:
        dockerfile: ./Dockerfile
    - image: onboarding
      context: platforms/onboarding
      docker:
        dockerfile: ./Dockerfile

