---
apiVersion: v1
kind: Service
metadata:
  name: app-02-service
  namespace: micro-frontend
  labels:
    app: app-02
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 3002
    nodePort: 30020
  selector:
    app: app-02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-02
  namespace: micro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-02
      version: v1
  template:
    metadata:
      labels:
        app: app-02
        version: v1
    spec:
      containers:
      - image: app-02
        imagePullPolicy: IfNotPresent
        name: app-02
        ports:
        - containerPort: 3002
