---
apiVersion: v1
kind: Service
metadata:
  name: app-03-service
  namespace: micro-frontend
  labels:
    app: app-03
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 3003
    nodePort: 30030
  selector:
    app: app-03
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-03
  namespace: micro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-03
      version: v1
  template:
    metadata:
      labels:
        app: app-03
        version: v1
    spec:
      containers:
      - image: app-03
        imagePullPolicy: IfNotPresent
        name: app-03
        ports:
        - containerPort: 3003
