---
apiVersion: v1
kind: Service
metadata:
  name: app-01-service
  namespace: micro-frontend
  labels:
    app: app-01
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 3001
    nodePort: 30010
  selector:
    app: app-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-01
  namespace: micro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-01
      version: v1
  template:
    metadata:
      labels:
        app: app-01
        version: v1
    spec:
      containers:
      - image: app-01
        imagePullPolicy: IfNotPresent
        name: app-01
        ports:
        - containerPort: 3001
