---
apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  namespace: micro-frontend
  labels:
    app: auth-app
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 3002
    nodePort: 30020
  selector:
    app: auth-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  namespace: micro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
      version: v1
  template:
    metadata:
      labels:
        app: auth-app
        version: v1
    spec:
      containers:
      - image: auth-app
        imagePullPolicy: IfNotPresent
        name: auth-app
        ports:
        - containerPort: 3002
