---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: micro-frontend
  labels:
    app: auth
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 3004
    nodePort: 30040
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: micro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      version: v1
  template:
    metadata:
      labels:
        app: auth
        version: v1
    spec:
      containers:
      - image: auth
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 3004
