---
apiVersion: v1
kind: Service
metadata:
  name: mothership-service
  namespace: micro-frontend
  labels:
    app: mothership
spec:
  type: NodePort
  ports:
  - name: web-port
    port: 3001
    nodePort: 30010
  selector:
    app: mothership
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mothership
  namespace: micro-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mothership
      version: v1
  template:
    metadata:
      labels:
        app: mothership
        version: v1
    spec:
      containers:
      - image: mothership
        imagePullPolicy: IfNotPresent
        name: mothership
        ports:
        - containerPort: 3001

